#
# Kernel makefile for TDMB(MTV818)
#

ifdef CONFIG_TDMB_MTV818
EXTRA_CFLAGS += -I.
endif

obj-y	+= mtv.o \
							mtv_i2c.o \
							mtv_spi.o \
							mtv_isr.o \
							raontv.o \
							raontv_port.o \
							raontv_rf.o \
							raontv_isdbt.o
